name: Node.js CI/CD

on:
  push:
    branches:
      - main      # se il tuo branch principale è master, cambia in master

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      SUPER_SECRET: ${{ secrets.SUPER_SECRET }}
      DB_URL: ${{ secrets.DB_URL }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - run: npm ci
      - run: npm run build
      - run: npm test

  deploy:
    name: Deploy to Render
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deploy
        uses: sws2apps/render-deployment@main
        with:
          serviceId: ${{ secrets.RENDER_ID }}
          apiKey: ${{ secrets.RENDER_API_KEY }}
          multipleDeployment: false